[package]
name = "git-branch-cleaner"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
git2 = "0.18.1"
ratatui = "0.23.0"
